### ISSUE TITLE
[Core] Block type "block"

### ISSUE THREAD

**Issue by h45h74x** [h45h74x/mc-source#3]
The "block" type represents a solid block and is used per default, if not otherwise specified. It represents a solid cube in the game world.

#### Tasks:

- [x] Update [Configuration.md](https://github.com/h45h74x/mc-source/blob/master/McSource/Configuration.md)
- [x] Handle custom entity data, if applicable
- [x] Handle properties, if applicable
- [x] Implement custom behaviours, if applicable
