### ISSUE TITLE
Block type "Ignored"

### ISSUE THREAD

**Issue by h45h74x** [h45h74x/mc-source#4]
This type represents a block that will not be processed by the converter.

#### Tasks:

- [x] Update [Configuration.md](https://github.com/h45h74x/mc-source/blob/master/McSource/Configuration.md)
- [x] Handle custom entity data, if applicable
- [x] Handle properties, if applicable
- [x] Implement custom behaviours, if applicable
